= Error Messages
:description: The standardized error codes returned by the Couchbase Python SDK, from cloud connection to sub-document.
:page-topic-type: reference

include::project-docs:partial$attributes.adoc[]

[abstract]
{description}

include::{version-server}@sdk:shared:partial$error-ref.adoc[tag=intro]

== Shared Error Definitions

include::{version-server}@sdk:shared:partial$error-ref.adoc[tag=shared]


== KeyValue Error Definitions
include::{version-server}@sdk:shared:partial$error-ref.adoc[tag=kv]


== Query Error Definitions
include::{version-server}@sdk:shared:partial$error-ref.adoc[tag=query]


== Analytics Error Definitions
include::{version-server}@sdk:shared:partial$error-ref.adoc[tag=analytics]


== Search Error Definition
include::{version-server}@sdk:shared:partial$error-ref.adoc[tag=search]


== View Error Definitions
include::{version-server}@sdk:shared:partial$error-ref.adoc[tag=views]


== Management API Error Definitions
include::{version-server}@sdk:shared:partial$error-ref.adoc[tag=mgmnt]


== Field-Level Encryption Error Definitions
include::{version-server}@sdk:shared:partial$error-ref.adoc[tag=fle]


////
=== SDK-Specific Error Definitions

ID Range 1000 - 2000

This range is reserved for sdk-specific error codes which are not standardized, but might be used later.
////



== Connecting to Cloud
include::{version-server}=@sdk:shared:partial$error-ref.adoc[tag=cloud]

.Couldn't look up
[source,terminal]
----
ERROR:couchbase.connection:[2302468477383294429] <8676842d-4e8b-4c5b-a44f-e0886f8c0bc1.dp.cloud.couchbase.com:18091> (SOCK=a95ae0d1210d3132) Couldn't look up 8676842d-4e8b-4c5b-a44f-e0886f8c0bc1.dp.cloud.couchbase.com (nodename nor servname provided, or not known) [EAI=8] (L:503)
----

.Failed to establish connection
[source,terminal]
----
ERROR:couchbase.connection:[2302468477383294429] <8676842d-4e8b-4c5b-a44f-e0886f8c0bc1.dp.cloud.couchbase.com:18091> (SOCK=a95ae0d1210d3132) Failed to establish connection: LCB_ERR_UNKNOWN_HOST (1049), os errno=0 (L:164)
----

.Connection to REST API failed
[source,terminal]
----
ERROR:couchbase.htconfig:[2302468477383294429] Connection to REST API failed with LCB_ERR_UNKNOWN_HOST (1049) (os errno = 0) (L:309)
----

.Provider 'HTTP' failed
[source,terminal]
----
INFO:couchbase.confmon:[2302468477383294429] Provider 'HTTP' failed: LCB_ERR_UNKNOWN_HOST (1049) (L:196)
----


== Further Reading

* Our practical look at xref:howtos:error-handling.adoc[error handling with the SDK].
// * xref:howtos:health-check.adoc#diagnostics[Diagnostics] with Health Check.
* xref:concept-docs:errors.adoc[Discussion document] on handling exceptions.
* Further reference material in the https://docs.couchbase.com/sdk-api/couchbase-python-client[API Guide].
